on: push
name: Go Web App Pipeline
jobs:
  Test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x, 1.16.x, 1.17.x, 1.18.x]
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: "Prepare go"
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: "Run tests"
        run: go test
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy app to Heroku"
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 9c997b61-900c-462f-970b-c9fb28bae09d
          heroku_app_name: "go-app-heroku-cicd-example"
          heroku_email: "ignat.belousov2000@yahoo.com"