on: push
name: Go Web App Pipeline

jobs:
  Test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x, 1.16.x, 1.17.x, 1.18.x]
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ubuntu-latest
    steps:
      - name: "Run tests"
        uses: actions/setup-go@3
        with:
          go-version: 1.16.x
        run: go test