on: push
name: Go Web App Pipeline

jobs:
  Test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x, 1.16.x, 1.17.x, 1.18.x]
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: "Prepare go"
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: "Run tests"
        run: go test